name: Publish
on:
  push:
    branches:
      - Prod

jobs:
  archi_report:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    name: Deploy Archi report HTML to GitHub Pages
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy Archi report
        id: archi
        uses: WoozyMasta/archimate-ci-image@4.9.2-1.0.3
        with:
          archiHtmlReportEnabled: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add CNAME record to GitHub Pages
        run: |
          echo "archi.ommat.ru" > CNAME
          git config --global user.email "datrefilov@edu.hse.ru"
          git config --global user.name "Trefilov Dmitriy Aleksandrovich"
          git add .
          git commit -m "Add CNAME record"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
